#include "AppTranslator.h"

#include <cstring>

namespace {
struct TranslationEntry {
    const char *source;
    const char *english;
};

const TranslationEntry translations[] = {
    {"TLockGUI - drand/tlock 大文件时间锁", "TLockGUI - drand/tlock Large File Timelock"},
    {"模式：", "Mode:"},
    {"加密", "Encrypt"},
    {"解密", "Decrypt"},
    {"界面语言：", "Language:"},
    {"简体中文", "Simplified Chinese"},
    {"绝对解锁时间：", "Unlock date and time:"},
    {"10 分钟后", "In 10 minutes"},
    {"1 小时后", "In 1 hour"},
    {"1 天后", "In 1 day"},
    {"7 天后", "In 7 days"},
    {"30 天后", "In 30 days"},
    {"180 天后", "In 180 days"},
    {"1 年后", "In 1 year"},
    {"文件名", "File name"},
    {"大小", "Size"},
    {"完整路径", "Full path"},
    {"输出文件", "Output file"},
    {"状态", "Status"},
    {"进度", "Progress"},
    {"添加文件...", "Add files..."},
    {"移除选中", "Remove selected"},
    {"清空列表", "Clear list"},
    {"输出设置", "Output settings"},
    {"与源文件相同目录", "Same directory as source"},
    {"指定目录", "Specific directory"},
    {"请选择已有且可写的输出目录", "Choose an existing writable output directory"},
    {"选择目录...", "Choose directory..."},
    {"官方 tle.exe", "Official tle.exe"},
    {"浏览...", "Browse..."},
    {"测试", "Test"},
    {"尚未验证", "Not verified"},
    {"tle.exe：", "tle.exe:"},
    {"任务状态（进度为 .part 文件大小估算）", "Task status (progress is estimated from .part size)"},
    {"最近活动：—", "Latest activity: —"},
    {"最近活动：%1", "Latest activity: %1"},
    {"运行中：0 / 1", "Running: 0 / 1"},
    {"运行中：%1 / %2", "Running: %1 / %2"},
    {"约进度：—", "Est. progress: —"},
    {"约进度：%1%", "Est. progress: %1%"},
    {"速度：—", "Speed: —"},
    {"速度：%1", "Speed: %1"},
    {"已用：—", "Elapsed: —"},
    {"已用：%1", "Elapsed: %1"},
    {"预计剩余：—", "ETA: —"},
    {"预计剩余：%1", "ETA: %1"},
    {"已完成 0 / 0", "Completed 0 / 0"},
    {"已完成 %1 / %2", "Completed %1 / %2"},
    {"已成功 0 B / 0 B", "Succeeded 0 B / 0 B"},
    {"已成功 %1 / %2", "Succeeded %1 / %2"},
    {"总进度约 %p%", "Total est. %p%"},
    {"处理期间阻止系统自动睡眠", "Prevent automatic sleep while processing"},
    {"仅阻止 Windows 因空闲而自动睡眠；屏幕仍可关闭，合盖、低电量和手动睡眠不受影响。", "Prevents idle sleep only. The display may turn off; lid close, low battery, and manual sleep are unaffected."},
    {"全部完成后关机", "Shut down after all tasks finish"},
    {"仅在批次没有失败或取消时安排 60 秒后关机；开始任务前会再次确认。", "Schedules shutdown in 60 seconds only if the batch has no failures or cancellations; confirmation is required before starting."},
    {"取消计划关机", "Cancel scheduled shutdown"},
    {"开始批处理", "Start batch"},
    {"取消选中任务", "Cancel selected tasks"},
    {"停止全部", "Stop all"},
    {"高级设置", "Advanced settings"},
    {"使用 tle 默认网络和 quicknet chain（不传 -n/-c）", "Use tle default network and quicknet chain (omit -n/-c)"},
    {"同时运行的 tle.exe 数量。默认 2；批次包含机械硬盘输入且数值大于 1 时，开始前会建议改为 1。", "Number of tle.exe processes to run at once. The default is 2; before a batch with HDD input starts, values above 1 trigger a recommendation to use 1."},
    {"并行任务数：", "Parallel tasks:"},
    {"日志", "Log"},
    {"本机时区：%1", "Local time zone: %1"},
    {"无法继续", "Cannot continue"},
    {"未找到 tle.exe", "tle.exe not found"},
    {"未按预设顺序找到 tle.exe，请手动选择。", "tle.exe was not found in the standard locations. Select it manually."},
    {"tle.exe 不存在", "tle.exe does not exist"},
    {"正在执行 --metadata...", "Running --metadata..."},
    {"测试 tle.exe：\n程序：\n%1\n参数：\n--metadata", "Testing tle.exe:\nProgram:\n%1\nArguments:\n--metadata"},
    {"无法启动", "Could not start"},
    {"tle.exe 启动失败：%1", "Failed to start tle.exe: %1"},
    {"tle.exe 可用", "tle.exe is ready"},
    {"tle.exe --metadata 测试成功。\n%1", "tle.exe --metadata succeeded.\n%1"},
    {"测试超时", "Test timed out"},
    {"metadata 测试失败", "Metadata test failed"},
    {"tle.exe --metadata 失败（退出代码 %1）。\n%2", "tle.exe --metadata failed (exit code %1).\n%2"},
    {"tle.exe --metadata 超过 15 秒，已终止测试。", "tle.exe --metadata exceeded 15 seconds and was terminated."},
    {"选择官方 tle.exe", "Select the official tle.exe"},
    {"tle.exe (tle.exe);;可执行文件 (*.exe);;所有文件 (*)", "tle.exe (tle.exe);;Executables (*.exe);;All files (*)"},
    {"已忽略 %1 个重复路径、目录或不存在的文件。", "Ignored %1 duplicate paths, directories, or missing files."},
    {"选择要处理的文件", "Select files to process"},
    {"所有文件 (*)", "All files (*)"},
    {"约 %p%", "Est. %p%"},
    {"计算中", "Calculating"},
    {"未计算", "Not calculated"},
    {"右键选择“计算 SHA-256”", "Right-click and choose Calculate SHA-256"},
    {"选择输出目录", "Select output directory"},
    {"已安排系统关机", "Shutdown already scheduled"},
    {"请先点击“取消计划关机”，再开始新的批处理。", "Cancel the scheduled shutdown before starting a new batch."},
    {"tle.exe 尚不可用", "tle.exe is not ready"},
    {"请先使用“测试”按钮确认官方 tle.exe 的 --metadata 测试成功。", "Use Test to confirm that the official tle.exe passes the --metadata check."},
    {"解锁时间无效", "Invalid unlock time"},
    {"目标解锁时间必须晚于当前时间。", "The unlock time must be later than the current time."},
    {"高级设置无效", "Invalid advanced settings"},
    {"自定义网络模式下 Network 和 Chain 都不能为空。", "Network and Chain are required when using a custom network."},
    {"无法开始", "Cannot start"},
    {"磁盘空间不足", "Insufficient disk space"},
    {"检测到机械硬盘输入", "HDD input detected"},
    {"Windows 检测到以下输入盘为机械硬盘：\n%1", "Windows identified these input volumes as HDDs:\n%1"},
    {"当前并发为 %1。多个 tle.exe 同时读取同一机械硬盘会导致磁头来回寻道，总速度通常更慢。建议本批次改为并发 1；SSD/NVMe 默认仍为 2。", "The current concurrency is %1. Multiple tle.exe processes reading the same HDD cause head seeking and usually reduce total throughput. Concurrency 1 is recommended for this batch; the SSD/NVMe default remains 2."},
    {"使用 1（推荐）", "Use 1 (recommended)"},
    {"保持 %1", "Keep %1"},
    {"检测到机械硬盘输入：%1。本批次并发已调整为 1。", "HDD input detected: %1. Concurrency was adjusted to 1 for this batch."},
    {"检测到机械硬盘输入：%1。用户选择保留并发 %2。", "HDD input detected: %1. The user kept concurrency %2."},
    {"、", ", "},
    {"确认完成后关机", "Confirm shutdown after completion"},
    {"本批次全部处理完成且没有失败或取消时，Windows 将在 60 秒后关机。\n关机前可使用“取消计划关机”按钮撤销。\n请先保存其他程序中未保存的内容；倒计时结束时 Windows 可能强制关闭应用。\n\n是否按此设置开始？", "Windows will shut down in 60 seconds after every task completes with no failures or cancellations.\nUse Cancel scheduled shutdown during the countdown to abort it.\nSave unsaved work in other applications; Windows may force applications to close when the countdown ends.\n\nStart with this setting?"},
    {"开始并行批处理，共 %1 个文件，并发上限 %2，总输入大小 %3。", "Starting parallel batch: %1 files, concurrency limit %2, total input %3."},
    {"请先添加至少一个文件。", "Add at least one file first."},
    {"输入文件不存在或不是普通文件：\n%1", "The input is missing or is not a regular file:\n%1"},
    {"输入文件为空：\n%1", "The input file is empty:\n%1"},
    {"输出文件不能与输入文件相同：\n%1", "The output file cannot be the same as the input:\n%1"},
    {"多个输入文件会生成同一个输出文件：\n%1\n请改用源文件目录或调整文件名。", "Multiple inputs would create the same output file:\n%1\nUse source directories or rename the files."},
    {"输出卷 %1 空间明显不足。\n批量保守估算需要：%2\n当前可用：%3\n估算包含每个文件 64 MiB 安全余量。", "Output volume %1 does not have enough space.\nConservative batch estimate: %2\nAvailable: %3\nThe estimate includes a 64 MiB safety margin per file."},
    {"已请求 Windows 在批处理期间保持唤醒（允许屏幕关闭）。", "Windows will stay awake while the batch runs (the display may turn off)."},
    {"警告：无法阻止系统自动睡眠：%1", "Warning: could not prevent automatic sleep: %1"},
    {"警告：恢复 Windows 默认睡眠策略失败：%1", "Warning: could not restore the default Windows sleep policy: %1"},
    {"已恢复 Windows 默认睡眠策略。", "Restored the default Windows sleep policy."},
    {"批处理结束：成功 %1，失败 %2，跳过 %3，取消 %4。", "Batch finished: %1 succeeded, %2 failed, %3 skipped, %4 cancelled."},
    {"批处理已%1。\n成功：%2\n失败：%3\n跳过：%4\n取消：%5", "Batch %1.\nSucceeded: %2\nFailed: %3\nSkipped: %4\nCancelled: %5"},
    {"\n\n失败详情（最多显示 3 项）：\n%1", "\n\nFailure details (up to 3):\n%1"},
    {"\n另有 %1 个失败任务，请查看日志或将鼠标停在表格“状态”列上查看详情。", "\n%1 more tasks failed. Check the log or hover over the Status column for details."},
    {"停止", "stopped"},
    {"完成", "completed"},
    {"\n\n请确认密文已经正确保存和备份后，再自行决定是否删除原始文件。TLockGUI 不会删除任何输入文件。", "\n\nVerify that encrypted files were saved and backed up before deciding whether to delete the originals. TLockGUI never deletes input files."},
    {"已安排 Windows 在 60 秒后关机。可点击“取消计划关机”撤销。", "Windows shutdown is scheduled in 60 seconds. Click Cancel scheduled shutdown to abort."},
    {"\n\n已安排 Windows 在 60 秒后关机。需要时请点击“取消计划关机”。", "\n\nWindows shutdown is scheduled in 60 seconds. Click Cancel scheduled shutdown if needed."},
    {"自动关机安排失败：%1", "Could not schedule automatic shutdown: %1"},
    {"\n\n未能安排自动关机：%1", "\n\nCould not schedule automatic shutdown: %1"},
    {"由于批次被停止、存在失败或取消任务，未执行自动关机。", "Automatic shutdown was suppressed because the batch was stopped or a task failed or was cancelled."},
    {"\n\n由于存在失败、取消或手动停止，未执行自动关机。", "\n\nAutomatic shutdown was suppressed because of a failure, cancellation, or manual stop."},
    {"取消关机失败", "Failed to cancel shutdown"},
    {"取消计划关机失败：%1", "Failed to cancel scheduled shutdown: %1"},
    {"已取消计划关机。", "Scheduled shutdown cancelled."},
    {"目标文件已存在", "Output file already exists"},
    {"目标文件已存在：\n%1\n\nTLockGUI 不会预先删除它；选择覆盖时，将在新 .part 完成后进行安全替换。", "The output file already exists:\n%1\n\nTLockGUI will not delete it first. If Overwrite is selected, it will be safely replaced only after the new .part file is complete."},
    {"覆盖", "Overwrite"},
    {"跳过", "Skip"},
    {"全部覆盖", "Overwrite all"},
    {"全部跳过", "Skip all"},
    {"取消整个任务", "Cancel entire batch"},
    {"计算 SHA-256", "Calculate SHA-256"},
    {"复制 SHA-256", "Copy SHA-256"},
    {"计算中 0%", "Calculating 0%"},
    {"开始后台计算 SHA-256：%1", "Calculating SHA-256 in the background: %1"},
    {"计算中 %1%", "Calculating %1%"},
    {"SHA-256 完成：%1\n%2", "SHA-256 completed: %1\n%2"},
    {"计算失败", "Calculation failed"},
    {"SHA-256 未完成：%1\n%2", "SHA-256 did not complete: %1\n%2"},
    {"已复制 SHA-256：%1", "Copied SHA-256: %1"},
    {"当前仍在处理大文件", "Large files are still being processed"},
    {"强制退出会终止所有运行中的任务并删除本次生成的 .part，但不会删除原始文件。\n\n是否退出？", "Exiting now will terminate every running task and delete .part files created by this run. Input files will not be deleted.\n\nExit now?"},
    {"语言设置已保存", "Language setting saved"},
    {"重新启动 TLockGUI 后将使用所选语言。", "Restart TLockGUI to use the selected language."},

    {"计算中...", "Calculating..."},
    {"约 %1/s", "About %1/s"},
    {"%1天 %2:%3:%4", "%1 days %2:%3:%4"},
    {"等待中", "Pending"},
    {"正在加密", "Encrypting"},
    {"正在解密", "Decrypting"},
    {"成功", "Succeeded"},
    {"失败", "Failed"},
    {"已跳过", "Skipped"},
    {"已取消", "Cancelled"},
    {"未知", "Unknown"},
    {"输出目录不存在：%1", "The output directory does not exist: %1"},
    {"输出目录不可写：%1\n%2", "The output directory is not writable: %1\n%2"},

    {"内部错误：已有 tle.exe 进程正在运行。", "Internal error: a tle.exe process is already running."},
    {"\ntle.exe 异常终止。", "\ntle.exe terminated unexpectedly."},
    {"\ntle.exe 返回成功，但临时输出文件不存在或为空。", "\ntle.exe returned success, but the temporary output is missing or empty."},
    {"无法读取文件：%1", "Could not read the file: %1"},
    {"SHA-256 计算已取消。", "SHA-256 calculation was cancelled."},
    {"读取文件失败：%1", "Failed to read the file: %1"},

    {"Windows 拒绝更新电源请求，错误代码：%1", "Windows rejected the power request. Error code: %1"},
    {"阻止自动睡眠仅支持 Windows。", "Preventing automatic sleep is supported only on Windows."},
    {"TLockGUI 批处理已成功完成。若需取消，请在 TLockGUI 中点击“取消计划关机”。", "The TLockGUI batch completed successfully. To abort shutdown, click Cancel scheduled shutdown in TLockGUI."},
    {"找不到 Windows shutdown.exe。", "Windows shutdown.exe was not found."},
    {"无法启动 shutdown.exe：%1", "Could not start shutdown.exe: %1"},
    {"shutdown.exe 未在预期时间内返回。", "shutdown.exe did not return within the expected time."},
    {"shutdown.exe 执行失败，退出代码：%1", "shutdown.exe failed with exit code %1."},
    {"shutdown.exe 执行失败：%1", "shutdown.exe failed: %1"},
    {"自动关机仅支持 Windows。", "Automatic shutdown is supported only on Windows."},

    {"正在取消任务 %1；将先请求进程正常终止，2 秒后仍未退出则强制结束。", "Cancelling task %1. The process will be asked to exit normally, then killed after 2 seconds if necessary."},
    {"用户取消了该任务。", "The user cancelled this task."},
    {"已取消：%1", "Cancelled: %1"},
    {"用户停止了批处理。", "The user stopped the batch."},
    {"正在停止全部 %1 个运行中的任务。", "Stopping all %1 running tasks."},
    {"用户取消了批处理。", "The user cancelled the batch."},
    {"程序退出时任务被终止。", "The task was terminated while the application was exiting."},
    {"输入文件不存在或不是普通文件：%1", "The input is missing or is not a regular file: %1"},
    {"输入文件为空，未启动 tle.exe：%1", "The input file is empty; tle.exe was not started: %1"},
    {"目标解锁时间已经到达或过去，无法继续生成时间锁文件。", "The unlock time has arrived or passed; no more timelock files can be created."},
    {"输出磁盘空间不足。至少需要 %1，可用 %2。", "Insufficient output disk space. At least %1 is required; %2 is available."},
    {"临时输出路径已存在。为保护现有数据，未覆盖该文件：%1\n请确认后手动移动或删除它，再重试。", "The temporary output path already exists. It was not overwritten to protect existing data: %1\nInspect it, then move or delete it manually before retrying."},
    {"开始加密 [%1/%2]：%3", "Starting encryption [%1/%2]: %3"},
    {"解锁目标：%1\n剩余：%2 秒", "Unlock target: %1\nRemaining: %2 seconds"},
    {"开始解密 [%1/%2]：%3", "Starting decryption [%1/%2]: %3"},
    {"程序：\n%1\n参数：\n%2", "Program:\n%1\nArguments:\n%2"},
    {"目标文件已存在，已按用户选择跳过。", "The output file already exists and was skipped as requested."},
    {"已跳过：%1", "Skipped: %1"},
    {"tle.exe [%1/%2] 已退出，退出代码：%3", "tle.exe [%1/%2] exited with code %3."},
    {"进程诊断信息：\n%1", "Process diagnostics:\n%1"},
    {"成功：%1\n输出：%2", "Succeeded: %1\nOutput: %2"},
    {"安全保存失败：%1", "Safe output finalization failed: %1"},
    {"失败：%1", "Failed: %1"},
    {"批处理已停止。", "The batch has stopped."},
    {"警告：无法删除临时文件，请手动处理：%1", "Warning: the temporary file could not be deleted. Handle it manually: %1"},
    {"临时输出不存在或为空：%1", "The temporary output is missing or empty: %1"},
    {"处理期间目标文件出现，为保护数据未覆盖：%1", "The output appeared during processing and was not overwritten to protect data: %1"},
    {"无法将临时文件重命名为最终文件：%1", "Could not rename the temporary file to the final output: %1"},
    {"无法暂存已有目标文件，原文件保持不变：%1", "Could not stage the existing output; the original remains unchanged: %1"},
    {"新文件重命名失败；已有目标文件已恢复。", "Renaming the new file failed; the existing output was restored."},
    {"新文件重命名失败，并且旧文件恢复失败。旧文件保存在：%1", "Renaming the new file failed, and restoring the old file also failed. The old file is at: %1"},
    {"警告：新文件已保存，但旧文件备份未能删除：%1", "Warning: the new file was saved, but the old backup could not be deleted: %1"},
    {"尚未到达解锁轮次。预计可解密时间：%1（%2）；按当前轮次估计还需约 %3。目标轮次：%4，当前轮次：%5。drand 节点可能有数秒延迟，请到时稍后重试。", "The unlock round has not arrived. Estimated decryptable time: %1 (%2); about %3 remains based on the current round. Target round: %4; current round: %5. drand nodes can lag by a few seconds, so retry shortly after that time."},
    {"尚未到达解锁轮次。目标轮次：%1，当前轮次：%2，还差 %3 轮。当前使用的网络周期未知，无法准确换算本地解密时间。", "The unlock round has not arrived. Target round: %1; current round: %2; %3 rounds remain. The current network period is unknown, so the local decryption time cannot be calculated accurately."},
    {"尚未到达解锁时间，tle.exe 未返回可换算的目标轮次。请稍后重试。退出代码：%1", "The unlock time has not arrived, and tle.exe did not return a target round that can be converted. Retry later. Exit code: %1"},
    {"输出磁盘可能已满。tle.exe 退出代码：%1", "The output disk may be full. tle.exe exit code: %1"},
    {"无法访问 drand 网络，请检查网络连接和高级网络设置。tle.exe 退出代码：%1", "Could not access the drand network. Check the connection and advanced network settings. tle.exe exit code: %1"},
    {"tle.exe 执行失败（退出代码 %1）：%2", "tle.exe failed (exit code %1): %2"},
    {"tle.exe 执行失败，退出代码：%1", "tle.exe failed with exit code %1."}
};
}

AppTranslator::AppTranslator(QObject *parent)
    : QTranslator(parent)
{
}

bool AppTranslator::isEmpty() const
{
    return false;
}

QString AppTranslator::translate(const char *context, const char *sourceText,
                                 const char *disambiguation, int n) const
{
    Q_UNUSED(context);
    Q_UNUSED(disambiguation);
    Q_UNUSED(n);
    if (!sourceText)
        return {};
    for (const TranslationEntry &entry : translations) {
        if (std::strcmp(sourceText, entry.source) == 0)
            return QString::fromUtf8(entry.english);
    }
    return {};
}
